# Generated by Django 3.1.5 on 2021-01-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weacht_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('openid', models.CharField(max_length=100)),
                ('wechat_phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
