# Generated by Django 3.1.5 on 2021-01-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='weacht_name',
            new_name='wechat_name',
        ),
    ]
