# Generated by Django 3.1.5 on 2021-01-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210119_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wechat_phone',
            new_name='wechat_photo',
        ),
    ]
