# Generated by Django 3.1.5 on 2021-01-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=11)),
                ('openid', models.CharField(max_length=100, unique=True)),
                ('wechat_photo', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
