# Generated by Django 3.1.5 on 2021-01-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
